bookers2-sample/config/routes.rb
Rails.application.routes.draw do
  get 'searches/search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: 'homes#top'
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    # １つのbookに対していくつもコメントできるので、resoucesと複数形を使用する
    resources :book_comments, only: [:create, :destroy]
    # 1つのbookに対してユーザーは一回しかいいねができないようにする為、resourceと単数形を使用する
    resource :favorites, only: [:create, :destroy]
  end

  # create(follow)、destroy(unfollow)とfollows,followersの一覧用を追加
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
  	get 'follows' => 'relationships#follower', as: 'follows'
  	get 'followers' => 'relationships#followed', as: 'followers'
  end
  # 検索機能のルーティング
  get '/search', to: 'searches#search'



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

bookers2-sample/app/models/favorite.rb
class Favorite < ApplicationRecord
  # モデルの関連付け
  belongs_to :user
  belongs_to :book
end

bookers2-sample/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    # どのbookに対してかを取得している
    @book = Book.find(params[:book_id])
    # favorite.user_id = current_user.id favorite = Favorite.new（book_id: book.id）を1つにまとめた記述
    # @で定義したものを渡す　(book_id: @book.id) でないとエラーになる
    favorite = current_user.favorites.new(book_id: @book.id)
    # いいねした事を保存する
    favorite.save
    # 現在のページへ戻ってくる（リダイレクト）させる
    # redirect_to request.referer
  end

  def destroy
    # どのbookに対してかを取得している
    @book = Book.find(params[:book_id])
    # favorite.user_id = current_user.id favorite = Favorite.new（book_id: book.id）を1つにまとめた記述
    favorite = current_user.favorites.find_by(book_id: @book.id)
    # いいねを削除する
    favorite.destroy
    # 現在のページへ戻ってくる（リダイレクト）させる
    # redirect_to request.referer
  end

end

bookers2-sample/app/helpers/favorites_helper.rb
module FavoritesHelper
end

bookers2-sample/app/views/favorites/_favorite_btn.html.erb
<!--bookに対してログインユーザーがいいねしていればtrue, いいねしていなければfalse-->
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
    <i class="fas fa-heart" aria-hidden="true" style="color: red;"></i>
    <span style="color: red;"><%= book.favorites.count %></span>
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book), method: :post, remote: true do %>
    <i class="fas fa-heart" aria-hidden="true"></i>
    <%= book.favorites.count %>
  <% end %>
<% end %>

bookers2-sample/app/views/favorites/create.js.erb
$('.favorite-btn<%= @book.id %>').html("<%= j(render "favorites/favorite_btn", book: @book) %>");

bookers2-sample/app/views/favorites/destroy.js.erb
$('.favorite-btn<%= @book.id %>').html("<%= j(render "favorites/favorite_btn", book: @book) %>");